### ISSUE TITLE
Add restart steps to Common Issues section

### ISSUE THREAD

**Issue by kaganjd** [toolness/p5.js-docker#11]
I hit an error after `docker-compose up` that said: 
`ERROR: failed to create endpoint p5jsdocker_website_1 on network bridge: Bind for 0.0.0.0:8000 failed: port is already allocated`

To get it working, I did:
1. `docker-machine stop default`
2. `docker-machine start default`
3. `docker-machine env`
4. `eval "$(docker-machine env default)"`
5. `docker-compose up`

I'm not sure why this works, but I have to do it a lot with Docker so thought it may be worth adding to the "Common Issues" section

**Comment by toolness** [comment]
Great idea, thanks @kaganjd! Just added it to the README.
